### ISSUE TITLE
angular not defined

### ISSUE THREAD

**Issue by zymplsi** [m-brtn/angular-meteor-ngdialog#1]
Hi,
I got this error from the package.

Is there any other thing I should do to use this package? angular and angular-meteor is already defined in my program.

Uncaught TypeError: Cannot read property 'module' of undefined

rshashkov_angular-meteor-ngdialog.js:50 

```
  var m = angular.module('ngDialog', []); 
```

**Comment by m-brtn** [comment]
Its looks like your 'angular' variable is not defined, check again, that is Angular are in your project.
